
services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: telegram_bot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d telegram_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

  # Telegram Bot Application
  bot:
    build: .
    container_name: telegram_bot_app
    restart: unless-stopped
    environment:
      BOT_TOKEN: 8250207332:AAEL-Mo2QYVf-IJocDfLAFhxLV_ыафывафыва # bot token
      ADMIN_ID: 12345678 # admin id
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/telegram_bot # db credentials
      DB_POOL_SIZE: 10
      DB_MAX_OVERFLOW: 30
      DB_POOL_TIMEOUT: 30
      DB_POOL_RECYCLE: 3600
    volumes:
      - ./data:/app/data # Mount Excel file 
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot_network

volumes:
  postgres_data:
    driver: local

networks:
  bot_network:
    driver: bridge